basePath: /
host: carsrv.shilov.pro
info:
  contact: {}
  description: API Server for TodoList Application
  title: Repair App API
  version: "9.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
